apiVersion: v1
kind: Service
metadata:
  name: goodburguer-produto-service
  labels:
    app: goodburguer-produto-app
spec:
  type: LoadBalancer
  selector:
    app: goodburguer-produto-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080